version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    command: 
      - --api.insecure=true 
      - --providers.docker
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    restart: always
  
  aws:
    build: ./aws/
    container_name: aws-service
    networks:
      - proxy
    command: pipenv run python aws-service.py
    restart: always
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.aws-service.rule=Host(`aws.localhost`)"

  sketchfab:
    build: ./sketchfab/
    container_name: sketchfab-service
    networks:
      - proxy
    command: pipenv run python sketchfab-service.py
    restart: always
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.sketchfab-service.rule=Host(`sketchfab.localhost`)" 

  vimeo:
    build: ./vimeo/
    container_name: vimeo-service
    networks:
      - proxy
    command: pipenv run python vimeo-service.py
    restart: always
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.vimeo-service.rule=Host(`vimeo.localhost`)"

networks:
    proxy:
