version: '3'

services:
  proxy:
    container_name: proxy
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    restart: always

  sketchfab-service:
    build: ./sketchfab/
    container_name: sketchfab-service
    networks:
      - proxy
    command: pipenv run gunicorn -b 0.0.0.0:5000 sketchfab-service:app
    restart: always
    labels:
      - traefik.http.routers.sketchfab-service.rule=PathPrefix(`/sketchfab`)


  aws-service:
    build: ./aws/
    container_name: aws-service
    networks:
      - proxy
    command: python aws-service.py
    restart: always
    labels:
      - traefik.http.routers.aws-service.rule=PathPrefix(`/aws`)
      - traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/aws

  vimeo-service:
    build: ./vimeo/
    container_name: vimeo-service
    networks:
      - proxy
    command: pipenv run gunicorn -b 0.0.0.0:5000 vimeo-service:app
    restart: always
    labels:
      - traefik.http.routers.vimeo-service.rule=PathPrefix(`/vimeo`)

networks:
    proxy:
